
# General imports

from AssignClassDialog import AssignClassDialog
from ComputeCompactRatioDialog import ComputeCompactRatioDialog
from ManualCheckDialog import ManualCheckDialog
from SpatialJoinDialog import SpatialJoinDialog
from ProgressDialog import ProgressDialog
from SpatialJoinMaxAreaDialog import SpatialJoinMaxAreaDialog
