
# General imports

from AssignClassDialog import AssignClassDialog
from ComputeCompactRatioDialog import ComputeCompactRatioDialog
from ManualCheckDialog import ManualCheckDialog
from SpatialJoinDialog import SpatialJoinDialog
